//
// Code auto-generated by initpackage (XSPEC12 local 
// model package code generator).  Do not edit.
// Package: isgri_background
// Function body: isgri_backgroundFunctionMap.cxx

#include    "isgri_backgroundFunctionMap.h"

#include    <XSModelFunction.h>

void 
createisgri_backgroundFunctionMap()
{


	XSFunctionMap["isgribackground"] = new XSCall<XSCCall>(isgribackgroundfunc);

}
