//
// Code auto-generated by initpackage (XSPEC12 local 
// model package code generator).  Do not edit.
// Package: isgri_background
// Function header: isgri_backgroundFunctionMap.h

#ifndef    FUNCTIONMAP_H
#define    FUNCTIONMAP_H

#include    <funcType.h>

class    XSModelFunction;

extern    ModelFunctionMap  XSFunctionMap;

void  createisgri_backgroundFunctionMap();

extern "C"  {


	XSCCall      isgribackgroundfunc;
}


#endif
