//
// Code auto-generated by initpackage (XSPEC12 local model package 
// code generator).  Do not edit
// Package: isgri_background Created :
// Initializer: isgri_background.cxx

#include <XSUser/UserInterface/xstcl.h>

#include  "isgri_backgroundFunctionMap.h"
#include  <XSModelFunction.h>

extern "C" int Isgri_background_Init(Tcl_Interp* tclInterp);
extern "C" int Isgri_background_SafeInit(Tcl_Interp* tclInterp);

int Isgri_background_Init(Tcl_Interp* tclInterp)
{
        return Isgri_background_SafeInit(tclInterp);
}

int Isgri_background_SafeInit(Tcl_Interp* tclInterp)
{

        char PACKAGE[] = "isgri_background";
        char VERSION[] = "1.0";
        Tcl_PkgProvide(tclInterp, PACKAGE, VERSION);
        createisgri_backgroundFunctionMap();

        char modeldat[255];
        snprintf(modeldat,255,"%s/isgri_background.dat",getenv("XSPECMODEL_ISGRIBACKGROUND") );

        XSModelFunction::updateComponentList
              (modeldat);
        return TCL_OK;

}

